services:
  dockscope:
    container_name: dockscope
    hostname: dockscope
    environment:
      PUID: 1027
      PGID: 100
      TZ: Europe/Istanbul
    volumes:
      - ../../_data:/data
    network_mode: nas
    ports:
      - 4681:4681
    restart: unless-stopped
    image: ghcr.io/manuelr-t/dockscope
