services:
  my-service:
    container_name: my-service
    hostname: my-service
    environment:
      PUID: 1027
      PGID: 100
      TZ: Europe/Istanbul
    volumes:
      - ../../_data:/data
    network_mode: nas
    restart: unless-stopped
    image: my-service:latest
